#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=deploy/aws-triage/scripts/perf-lib.sh
source "${SCRIPT_DIR}/perf-lib.sh"

perf_need_command "openssl" "Install openssl."

if [[ -e "${PERF_ENV_FILE}" ]]; then
  perf_fail "${PERF_ENV_FILE} already exists. It was not overwritten."
fi

umask 077
postgres_password="$(openssl rand -hex 24)"
auth_state_secret="$(openssl rand -hex 32)"
internal_service_token="$(openssl rand -hex 32)"
cache_key_secret="$(openssl rand -hex 32)"
demo_api_key="gsk_perf_$(openssl rand -hex 24)"
demo_app_token="gat_perf_$(openssl rand -hex 24)"

cat > "${PERF_ENV_FILE}" <<EOF
GATELM_PUBLIC_DOMAIN=127.0.0.1
GATELM_PUBLIC_BASE_URL=http://127.0.0.1:13000
GATELM_APPLICATION_BASE_URL=http://127.0.0.1:13002
AWS_TRIAGE_WEB_BIND=127.0.0.1
AWS_TRIAGE_WEB_PORT=13000
AWS_TRIAGE_APPLICATION_BIND=127.0.0.1
AWS_TRIAGE_APPLICATION_PORT=13002
AWS_TRIAGE_CONTROL_PLANE_BIND=127.0.0.1
AWS_TRIAGE_CONTROL_PLANE_PORT=13001
GATELM_PERF_REMOTE_LOADGEN_ENABLED=false
AWS_TRIAGE_GATEWAY_BIND=127.0.0.1
AWS_TRIAGE_GATEWAY_PORT=18080
POSTGRES_USER=gatelm_perf
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=gatelm_perf
CONTROL_PLANE_ADMIN_AUTH_MODE=session_cookie
CONTROL_PLANE_AUTH_COOKIE_SECURE=false
CONTROL_PLANE_AUTH_STATE_SECRET=${auth_state_secret}
CONTROL_PLANE_INTERNAL_SERVICE_TOKEN=${internal_service_token}
AUTH_EMAIL_TRANSPORT=smtp
CONTROL_PLANE_AUTH_DEV_AUTO_VERIFY=false
SMTP_HOST=127.0.0.1
SMTP_PORT=2525
SMTP_SECURE=false
SMTP_TLS_MODE=opportunistic
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=gatelm-perf@example.invalid
GOOGLE_OAUTH_CLIENT_ID=
GOOGLE_OAUTH_CLIENT_SECRET=
GOOGLE_OAUTH_REDIRECT_URI=http://127.0.0.1:13000/api/auth/google/callback
GATEWAY_RUNTIME_SNAPSHOT_MODE=strict
GATEWAY_CONTROL_PLANE_INTERNAL_TOKEN=${internal_service_token}
GATEWAY_CONTROL_PLANE_TIMEOUT_MS=5000
GATEWAY_PROVIDER_TIMEOUT_MS=5000
GATEWAY_DEFAULT_PROVIDER=mock
GATEWAY_DEFAULT_MODEL=mock-balanced
GATEWAY_LOW_COST_MODEL=mock-fast
GATEWAY_HIGH_QUALITY_MODEL=mock-smart
GATEWAY_EXACT_CACHE_KEY_SECRET=${cache_key_secret}
GATEWAY_MAX_REQUEST_BODY_BYTES=4194304
GATEWAY_RATE_LIMIT_ENABLED=true
GATEWAY_RATE_LIMIT_BACKEND=redis
GATEWAY_RATE_LIMIT_ALGORITHM=token_bucket
GATEWAY_RATE_LIMIT_WINDOW_SECONDS=60
GATEWAY_RATE_LIMIT_LIMIT=100000
GATEWAY_RATE_LIMIT_REDIS_KEY_PREFIX=gatelm:perf:rate-limit
GATEWAY_AI_SAFETY_SIDECAR_ENABLED=false
GATELM_DEMO_PROVIDER_MODE=mock
GATELM_PERF_RUNTIME_RATE_LIMIT_LIMIT=100000
MOCK_PROVIDER_DEFAULT_LATENCY_MS=100
GATELM_PROVIDER_CREDENTIAL_ENCRYPTION_KEY=
GATELM_PROVIDER_CREDENTIAL_ENCRYPTION_KEY_VERSION=v1
CONTROL_PLANE_PROVIDER_CREDENTIAL_ENV_MAP=
GATEWAY_PROVIDER_CREDENTIAL_ENV_MAP=
OPENAI_API_KEY=
GATELM_DEMO_API_KEY=${demo_api_key}
GATELM_DEMO_APP_TOKEN=${demo_app_token}
GATELM_DEMO_TENANT_ID=00000000-0000-4000-8000-000000000100
GATELM_DEMO_PROJECT_ID=00000000-0000-4000-8000-000000000200
GATELM_DEMO_APPLICATION_ID=00000000-0000-4000-8000-000000000300
GATELM_DEMO_API_KEY_ID=00000000-0000-4000-8000-000000000400
GATELM_DEMO_APP_TOKEN_ID=00000000-0000-4000-8000-000000000500
GATELM_WEB_CUSTOMER_DEMO_MODE=gateway
GATELM_WEB_RATE_LIMIT_MAX_ATTEMPTS=60
GATELM_APPLICATION_CHAT_MAX_TOKENS=2048
GATELM_APPLICATION_CHAT_ENV_SYNC=false
GATELM_GATEWAY_API_KEY=${demo_api_key}
GATELM_APPLICATION_CHAT_API_KEY=${demo_api_key}
GATELM_APPLICATION_CHAT_API_KEYS=
GATELM_APPLICATION_CHAT_PROFILES=
GATELM_CONTROL_PLANE_TENANT_ID=00000000-0000-4000-8000-000000000100
GATELM_CONTROL_PLANE_PROJECT_ID=00000000-0000-4000-8000-000000000200
GATELM_CONTROL_PLANE_APPLICATION_ID=00000000-0000-4000-8000-000000000300
AI_SERVICE_INSTALL_ML_DEPS=false
AI_SERVICE_LOG_LEVEL=INFO
AI_SERVICE_REMOTE_SAFETY_MODE=disabled
AI_SERVICE_ACCESS_LOG_ENABLED=false
AI_SERVICE_TRANSFORMERS_OFFLINE=1
AI_SERVICE_AI_SAFETY_DETECTOR_RUNTIME=onnx
AI_SERVICE_AI_SAFETY_DETECTOR_MODEL_ID=openai/privacy-filter
AI_SERVICE_AI_SAFETY_ADDITIONAL_DETECTOR_MODEL_IDS=
EOF

chmod 600 "${PERF_ENV_FILE}"
unset postgres_password auth_state_secret internal_service_token cache_key_secret demo_api_key demo_app_token

perf_load_env
perf_validate_env
perf_log "Created ${PERF_ENV_FILE} with mode 600. Secret values were not printed."
perf_log "Next: bash scripts/perf-up.sh --build"
