from __future__ import annotations

from dataclasses import dataclass


@dataclass
class RagExtractionError(Exception):
    code: str
    message: str
    status_code: int = 400
    retryable: bool = False


ERROR_AUTH_REQUIRED = "RAG_EXTRACTION_AUTH_REQUIRED"
ERROR_EMPTY_TEXT = "RAG_EXTRACTION_EMPTY_TEXT"
ERROR_INPUT_TOO_LARGE = "RAG_EXTRACTION_INPUT_TOO_LARGE"
ERROR_INVALID_ENCODING = "RAG_EXTRACTION_INVALID_ENCODING"
ERROR_INVALID_PDF = "RAG_EXTRACTION_INVALID_PDF"
ERROR_ENCRYPTED_PDF = "RAG_EXTRACTION_ENCRYPTED_PDF"
ERROR_PDF_PAGE_LIMIT = "RAG_EXTRACTION_PDF_PAGE_LIMIT_EXCEEDED"
ERROR_EXTRACTED_TEXT_LIMIT = "RAG_EXTRACTION_TEXT_LIMIT_EXCEEDED"
ERROR_PDF_TIMEOUT = "RAG_EXTRACTION_PDF_TIMEOUT"
ERROR_SCANNED_PDF = "RAG_EXTRACTION_SCANNED_PDF_NOT_SUPPORTED"
ERROR_CHUNK_LIMIT = "RAG_EXTRACTION_CHUNK_LIMIT_EXCEEDED"
ERROR_UNSUPPORTED_MEDIA_TYPE = "RAG_EXTRACTION_UNSUPPORTED_MEDIA_TYPE"
ERROR_UNAVAILABLE = "RAG_EXTRACTION_UNAVAILABLE"
