package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"gatelm/apps/gateway-core/internal/tools/difficultymodel"
)

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout io.Writer, stderr io.Writer) int {
	flags := flag.NewFlagSet("difficulty-model-codegen", flag.ContinueOnError)
	flags.SetOutput(stderr)
	artifactPath := flags.String("artifact", "", "versioned difficulty model artifact JSON")
	outputPath := flags.String("output", "", "generated Go output; use a temporary candidate path before promotion")
	profile := flags.String("profile", "", "optional strict generation profile")
	check := flags.Bool("check", false, "compare generated bytes with the existing output without writing")
	if err := flags.Parse(args); err != nil {
		return 2
	}
	if *artifactPath == "" || *outputPath == "" {
		fmt.Fprintln(stderr, "-artifact and -output are required")
		return 2
	}
	payload, err := os.ReadFile(*artifactPath)
	if err != nil {
		fmt.Fprintln(stderr, "read model artifact:", err)
		return 1
	}
	var generated []byte
	switch *profile {
	case "":
		generated, err = difficultymodel.RenderArtifactPayload(payload, "routing")
	case difficultymodel.GatewayShadow118DProfileName:
		generated, err = difficultymodel.RenderGatewayShadow118DPayload(payload, "routing")
	case difficultymodel.GatewayShadow106DProfileName:
		generated, err = difficultymodel.RenderGatewayShadow106DPayload(payload, "routing")
	default:
		fmt.Fprintln(stderr, "unsupported generation profile:", *profile)
		return 2
	}
	if err != nil {
		fmt.Fprintln(stderr, err)
		return 1
	}
	if *check {
		existing, readErr := os.ReadFile(*outputPath)
		if readErr != nil {
			fmt.Fprintln(stderr, "read generated output:", readErr)
			return 1
		}
		if !bytes.Equal(existing, generated) {
			fmt.Fprintln(stderr, "generated output does not match canonical artifact")
			return 1
		}
		fmt.Fprintln(stdout, "generated output matches canonical artifact")
		return 0
	}
	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fmt.Fprintln(stderr, "create generated output directory:", err)
		return 1
	}
	if err := os.WriteFile(*outputPath, generated, 0o644); err != nil {
		fmt.Fprintln(stderr, "write generated Go model:", err)
		return 1
	}
	return 0
}
