// Code generated by difficulty-model-codegen; DO NOT EDIT.
package routing

var generatedDifficultyLogisticModelV1 = difficultyLogisticModel{
	artifactVersion: "difficulty-logistic.semantic-b1.model-path-5000.2026-07-19.v1",
	contentHash:     "sha256:6fdd46325175cb36189f33c2e590841165be13f081c44b982400da13f17d38a9",
	bias:            -2.7877951025358332,
	weights: [DifficultyFeatureVectorDimensionV1]float64{
		0.0,                  // payloadEmpty
		-2.2344779557612466,  // payloadSmall
		-0.55331714678430799, // payloadMedium
		0.0,                  // payloadLarge
		-0.54807923326772567, // taskCount
		5.5412800471836094,   // constraintCount
		12.213569527894718,   // scopeCount
		10.153157823992544,   // dependencyDepth
		-0.33858902212066055, // categoryGeneral
		-0.98688570443907897, // categoryCode
		-2.3203758565278561,  // categoryTranslation
		0.50427866772476915,  // categorySummarization
		0.35377681281513579,  // categoryReasoning
		-0.35537826053992566, // generalWorkflowDepth
		0.80315567560590617,  // generalBranchOrExceptionCount
		-0.83510903863255903, // generalExtractionBreadth
		3.7203062405529246,   // generalHasCrossSourceSynthesis
		0.51056185658619457,  // codeOperationUnknown
		0.0,                  // codeOperationSyntax
		2.4195838120930366,   // codeOperationExample
		0.0,                  // codeOperationSmallEdit
		-0.3145755574197312,  // codeOperationDebug
		-0.88217591255741667, // codeOperationRefactor
		0.0,                  // codeOperationDesign
		0.82856712335350513,  // codeOperationMigration
		-0.83291446159504889, // codeOperationConcurrency
		-2.7159325649024462,  // codeOperationPerformance
		2.2424325770444216,   // codeScopeBreadth
		-2.402095971402685,   // codeCausalComplexity
		-4.1776227416753935,  // codeEngineeringConstraintCount
		-0.58009396413196401, // translationScopeCount
		9.660033250811102,    // translationPreservationConstraintCount
		2.7664955800329905,   // translationDomainTerminologyLevel
		0.86672953350870008,  // translationLocalizationDegree
		-3.875509030780838,   // summarizationSourceBreadth
		2.8643302143832696,   // summarizationSynthesisLevel
		5.6553585612728003,   // summarizationFacetCount
		1.4020209421541197,   // summarizationHasTraceabilityConstraints
		-4.9173106940151641,  // reasoningAlternativeCount
		6.8291037359973554,   // reasoningCriteriaAndConstraintCount
		0.6662998096440248,   // reasoningDepth
		5.0416908431560064,   // reasoningUncertaintyScenarioCount
	},
	calibrator: difficultyCalibrator{
		kind:      difficultyCalibratorIsotonic,
		isotonicX: []float64{0.010099301907691212, 0.036491323708363353, 0.10855165273651267, 0.12560090874779051, 0.27195516344415172, 0.38934454201254992, 0.50609064196167353, 0.57723118313093591, 0.70622875339986013, 0.79160542695802161, 0.82706052069963043, 0.86004174568992686, 0.95028458858063358, 0.97130248933127206, 0.98597048946622012},
		isotonicY: []float64{0.0, 0.015873015873015872, 0.1388888888888889, 0.24087591240875914, 0.31521739130434784, 0.44067796610169491, 0.66666666666666663, 0.71186440677966101, 0.79411764705882348, 0.84615384615384615, 0.88888888888888884, 0.90540540540540537, 0.94871794871794868, 0.96666666666666667, 1.0},
	},
	threshold: 0.5,
}
