package difficultymodel

import (
	"encoding/json"
	"strings"
	"testing"

	"gatelm/apps/gateway-core/internal/domain/routing"
)

func TestValidateArtifactAndRenderGo(t *testing.T) {
	t.Parallel()
	artifact := validArtifact()
	if err := ValidateArtifact(artifact); err != nil {
		t.Fatal(err)
	}
	generated, err := RenderGo(artifact, "routing")
	if err != nil {
		t.Fatal(err)
	}
	text := string(generated)
	for _, marker := range []string{
		"Code generated by difficulty-model-codegen",
		"generatedDifficultyLogisticModelV1",
		"[DifficultyFeatureVectorDimensionV1]float64",
		artifact.ContentHash,
	} {
		if !strings.Contains(text, marker) {
			t.Fatalf("generated Go is missing %q:\n%s", marker, text)
		}
	}
}

func TestValidateArtifactAllowsNonInferenceMetadataChanges(t *testing.T) {
	t.Parallel()
	artifact := validArtifact()
	artifact.ArtifactVersion = ""
	artifact.TrainingDatasetVersion = ""
	artifact.TrainingDatasetSHA256 = "not-a-hash"
	artifact.SplitPolicyVersion = ""
	artifact.Regularization = Regularization{}
	if err := ValidateArtifact(artifact); err != nil {
		t.Fatalf("non-inference metadata must not block code generation: %v", err)
	}

	payload, err := json.Marshal(artifact)
	if err != nil {
		t.Fatal(err)
	}
	payload = append(payload[:len(payload)-1], []byte(`,"futureMetadata":{"note":"ignored by codegen"}}`)...)
	if _, err := ParseArtifact(payload); err != nil {
		t.Fatalf("unknown non-inference metadata must not block code generation: %v", err)
	}
}

func TestValidateArtifactRejectsInferenceShapeDrift(t *testing.T) {
	t.Parallel()
	tests := map[string]func(*Artifact){
		"model version":   func(artifact *Artifact) { artifact.ModelVersion = "difficulty-logistic-v2" },
		"feature version": func(artifact *Artifact) { artifact.FeatureVersion = "difficulty-feature-vector.v2" },
		"feature order": func(artifact *Artifact) {
			artifact.FeatureNames[0], artifact.FeatureNames[1] = artifact.FeatureNames[1], artifact.FeatureNames[0]
		},
		"weight count": func(artifact *Artifact) { artifact.Weights = artifact.Weights[:41] },
		"threshold":    func(artifact *Artifact) { artifact.Threshold = 0.5 },
		"content hash": func(artifact *Artifact) { artifact.ContentHash = "sha256:" + strings.Repeat("0", 64) },
	}
	for name, mutate := range tests {
		name := name
		mutate := mutate
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			artifact := validArtifact()
			mutate(&artifact)
			if err := ValidateArtifact(artifact); err == nil {
				t.Fatal("invalid artifact was accepted")
			}
		})
	}
}

func TestValidateArtifactRejectsInvalidIsotonicMaterial(t *testing.T) {
	t.Parallel()
	artifact := validArtifact()
	artifact.Calibrator = Calibrator{
		Type:        "isotonic",
		Input:       "raw_probability",
		XThresholds: []float64{0, 0.7, 0.6},
		YThresholds: []float64{0.1, 0.8, 0.9},
	}
	artifact.ContentHash = ContentHash(artifact)
	if err := ValidateArtifact(artifact); err == nil || !strings.Contains(err.Error(), "ordered") {
		t.Fatalf("invalid isotonic material error = %v", err)
	}
}

func TestValidateArtifactAcceptsSingleBlockIsotonicMaterial(t *testing.T) {
	t.Parallel()
	artifact := validArtifact()
	artifact.Calibrator = Calibrator{
		Type:        "isotonic",
		Input:       "raw_probability",
		XThresholds: []float64{0.35},
		YThresholds: []float64{0.6},
	}
	artifact.ContentHash = ContentHash(artifact)
	if err := ValidateArtifact(artifact); err != nil {
		t.Fatalf("single-block isotonic artifact was rejected: %v", err)
	}
	generated, err := RenderGo(artifact, "routing")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(generated), "isotonicX: []float64{") ||
		!strings.Contains(string(generated), "isotonicY: []float64{") {
		t.Fatalf("generated Go is missing single-block isotonic material:\n%s", generated)
	}
}

func TestValidateArtifactRejectsEmptyIsotonicMaterial(t *testing.T) {
	t.Parallel()
	artifact := validArtifact()
	artifact.Calibrator = Calibrator{Type: "isotonic", Input: "raw_probability"}
	artifact.ContentHash = ContentHash(artifact)
	if err := ValidateArtifact(artifact); err == nil || !strings.Contains(err.Error(), "thresholds are invalid") {
		t.Fatalf("empty isotonic material error = %v", err)
	}
}

func TestValidateArtifactRejectsIdentityAndMixedCalibratorMaterial(t *testing.T) {
	t.Parallel()
	tests := map[string]Calibrator{
		"identity": {
			Type:  "identity",
			Input: "raw_probability",
		},
		"platt with isotonic parameters": {
			Type:        "platt",
			Input:       "raw_probability",
			Coefficient: float64Ptr(1.24),
			Intercept:   float64Ptr(-0.31),
			XThresholds: []float64{0, 1},
			YThresholds: []float64{0.1, 0.9},
		},
		"isotonic with platt parameters": {
			Type:        "isotonic",
			Input:       "raw_probability",
			Coefficient: float64Ptr(1.24),
			XThresholds: []float64{0, 1},
			YThresholds: []float64{0.1, 0.9},
		},
	}
	for name, calibrator := range tests {
		name := name
		calibrator := calibrator
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			artifact := validArtifact()
			artifact.Calibrator = calibrator
			artifact.ContentHash = ContentHash(artifact)
			if err := ValidateArtifact(artifact); err == nil {
				t.Fatal("invalid calibrator material was accepted")
			}
		})
	}
}

func TestParseArtifactRejectsTopLevelCalibratorType(t *testing.T) {
	t.Parallel()
	artifact := validArtifact()
	payload, err := json.Marshal(artifact)
	if err != nil {
		t.Fatal(err)
	}
	payload = append(payload[:len(payload)-1], []byte(`,"calibratorType":"platt"}`)...)
	if _, err := ParseArtifact(payload); err == nil || !strings.Contains(err.Error(), "nested calibrator.type") {
		t.Fatalf("top-level calibratorType error = %v", err)
	}
}

func TestParseArtifactRejectsNonCanonicalCalibratorFieldsEvenWhenEmpty(t *testing.T) {
	t.Parallel()
	tests := map[string]map[string]any{
		"platt with empty isotonic field": {
			"type":        "platt",
			"input":       "raw_probability",
			"coefficient": 1.24,
			"intercept":   -0.31,
			"xThresholds": []float64{},
		},
		"isotonic with null platt field": {
			"type":        "isotonic",
			"input":       "raw_probability",
			"xThresholds": []float64{0.35},
			"yThresholds": []float64{0.6},
			"coefficient": nil,
		},
	}
	for name, calibrator := range tests {
		name := name
		calibrator := calibrator
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			artifact := validArtifact()
			payload, err := json.Marshal(artifact)
			if err != nil {
				t.Fatal(err)
			}
			var document map[string]any
			if err := json.Unmarshal(payload, &document); err != nil {
				t.Fatal(err)
			}
			document["calibrator"] = calibrator
			payload, err = json.Marshal(document)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := ParseArtifact(payload); err == nil || !strings.Contains(err.Error(), "canonical fields") {
				t.Fatalf("non-canonical calibrator fields error = %v", err)
			}
		})
	}
}

func validArtifact() Artifact {
	coefficient := 1.25
	intercept := -0.1
	artifact := Artifact{
		SchemaVersion:          ArtifactSchemaVersion,
		ArtifactVersion:        "difficulty-logistic-v1-toy-test",
		ModelVersion:           ModelVersion,
		FeatureVersion:         routing.DifficultyFeatureVectorVersionV1,
		TrainingDatasetVersion: "difficulty_toy_v1",
		TrainingDatasetSHA256:  strings.Repeat("a", 64),
		SplitPolicyVersion:     "difficulty-family-split.v1",
		Regularization: Regularization{
			PolicyVersion: "difficulty-logistic-training.v1",
			Penalty:       "l2",
			Solver:        "liblinear",
			SelectedC:     1,
			GroupFolds:    2,
			RandomSeed:    1729,
		},
		Bias:               -0.25,
		FeatureNames:       routing.DifficultyFeatureNamesV1(),
		Weights:            make([]float64, routing.DifficultyFeatureVectorDimensionV1),
		CalibrationVersion: CalibrationVersion,
		Calibrator: Calibrator{
			Type:        "platt",
			Input:       "raw_probability",
			Coefficient: &coefficient,
			Intercept:   &intercept,
		},
		ThresholdPolicyVersion: ThresholdPolicyVersion,
		Threshold:              ThresholdValue,
		ContentHashAlgorithm:   ContentHashAlgorithm,
	}
	for index := range artifact.Weights {
		artifact.Weights[index] = float64(index-20) / 100
	}
	artifact.ContentHash = ContentHash(artifact)
	return artifact
}

func float64Ptr(value float64) *float64 {
	return &value
}
